# Generated by Django 5.2.8 on 2025-12-10 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asignatura', models.CharField(max_length=255)),
                ('Nota_Obtenida', models.DecimalField(decimal_places=2, help_text='Nota obtenida en la asignatura', max_digits=5)),
                ('Fecha_Evaluacion', models.DateField()),
                ('N_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Calificación',
                'verbose_name_plural': 'Registros de Calificaciones',
            },
        ),
    ]
